In [1]:
%pip install neo4j

Collecting neo4j
  Downloading neo4j-6.3.1-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: pytz in C:\Python311\Lib\site-packages (from neo4j) (2024.1)
Downloading neo4j-6.3.1-py3-none-any.whl (331 kB)
Installing collected packages: neo4j
Successfully installed neo4j-6.3.1
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~ (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~~p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~~p (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~~p (C:\Python311\Lib\site-packages)

[notice] A new release of pip is available: 26.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
from getpass import getpass
from neo4j import GraphDatabase

# close the old connection if it is still open
try:
    driver.close()
except Exception:
    pass

NEO4J_URI  = "bolt://localhost:7688"      # new container (the old one used 7687)
NEO4J_USER = "neo4j"
NEO4J_PASSWORD = getpass("NEW Neo4j password: ")   # the password from docker-compose-bdv.yml

driver = GraphDatabase.driver(NEO4J_URI, auth=(NEO4J_USER, NEO4J_PASSWORD))
driver.verify_connectivity()

with driver.session(database="neo4j") as session:
    rec = session.run(
        "CALL dbms.components() YIELD name, versions RETURN name, versions[0] AS version"
    ).single()
    print("Connected to the NEW graph!", rec["name"], rec["version"])

NEW Neo4j password:  ········

Connected to the NEW graph! Neo4j Kernel 2026.06.0

C:\Python311\Lib\site-packages\neo4j\_sync\work\result.py:636: UserWarning: Expected a result with a single record, but found multiple.
  warn(

In [6]:
with driver.session(database="neo4j") as session:
    nodes = session.run("MATCH (n) RETURN count(n) AS n").single()["n"]
    rels  = session.run("MATCH ()-[r]->() RETURN count(r) AS n").single()["n"]
    rules = session.run("SHOW CONSTRAINTS YIELD name RETURN count(*) AS n").single()["n"]
    print("Nodes:", nodes, "| Relationships:", rels, "| Rules:", rules)

Nodes: 0 | Relationships: 0 | Rules: 0

In [7]:
rules = [
    "CREATE CONSTRAINT visitor_id_unique IF NOT EXISTS FOR (v:Visitor) REQUIRE v.visitor_id IS UNIQUE",
    "CREATE CONSTRAINT product_id_unique IF NOT EXISTS FOR (p:Product) REQUIRE p.item_id IS UNIQUE",
    "CREATE CONSTRAINT category_id_unique IF NOT EXISTS FOR (c:Category) REQUIRE c.category_id IS UNIQUE",
    "CREATE CONSTRAINT transaction_id_unique IF NOT EXISTS FOR (t:Transaction) REQUIRE t.transaction_id IS UNIQUE",
]

with driver.session(database="neo4j") as session:
    for rule in rules:
        session.run(rule).consume()
    print("Rules in the new graph:")
    for row in session.run("SHOW CONSTRAINTS YIELD name, labelsOrTypes, properties RETURN name, labelsOrTypes, properties"):
        print(" ", row["name"], "->", row["labelsOrTypes"], row["properties"])

Rules in the new graph:
  category_id_unique -> ['Category'] ['category_id']
  product_id_unique -> ['Product'] ['item_id']
  transaction_id_unique -> ['Transaction'] ['transaction_id']
  visitor_id_unique -> ['Visitor'] ['visitor_id']

*connect mysqsl*

In [9]:
import pandas as pd
from getpass import getpass
from urllib.parse import quote_plus
from sqlalchemy import create_engine, text

MYSQL_PASSWORD = getpass("MySQL password: ")
engine = create_engine(
    f"mysql+pymysql://root:{quote_plus(MYSQL_PASSWORD)}@localhost:3306/ecommerce_bdv"
)

def q(sql, params=None):
    with engine.connect() as conn:
        return pd.read_sql(text(sql), conn, params=params)

def to_rows(df):
    # plain Python values (None for empty) so Neo4j accepts them
    df = df.astype(object).where(df.notna(), None)
    return df.to_dict("records")

def run_batches(cypher, rows, batch_size=5000, label=""):
    total = len(rows)
    with driver.session(database="neo4j") as session:
        for i in range(0, total, batch_size):
            session.run(cypher, rows=rows[i:i + batch_size]).consume()
            done = min(i + batch_size, total)
            if (done // batch_size) % 10 == 0 or done == total:
                print(f"{label}: {done:,} / {total:,}")
    print(f"{label}: finished\n")

print("Baseline events in MySQL:", q("SELECT COUNT(*) AS n FROM events WHERE batch_id = 0")["n"][0])

MySQL password:  ········

Baseline events in MySQL: 1653660

*category nodes and parent link*

In [10]:
cats = q("SELECT category_id, parent_id, level, root_category_id FROM categories")
for col in ["parent_id", "level", "root_category_id"]:
    cats[col] = cats[col].astype("Int64")

run_batches("""
    UNWIND $rows AS r
    MERGE (c:Category {category_id: r.category_id})
    SET c.level = r.level, c.root_category_id = r.root_category_id
""", to_rows(cats), label="Category nodes")

with_parent = cats[cats["parent_id"].notna()][["category_id", "parent_id"]]
run_batches("""
    UNWIND $rows AS r
    MATCH (c:Category {category_id: r.category_id})
    MATCH (p:Category {category_id: r.parent_id})
    MERGE (c)-[:CHILD_OF]->(p)
""", to_rows(with_parent), label="CHILD_OF links")

Category nodes: 1,699 / 1,699
Category nodes: finished

CHILD_OF links: 1,644 / 1,644
CHILD_OF links: finished

*product nodes and categories*

In [11]:
cutoff = q("SELECT MAX(event_time) AS t FROM events WHERE batch_id = 0")["t"][0]
print("Baseline cutoff time:", cutoff)

prods = q("""
    SELECT p.item_id, h.category_id
    FROM (SELECT DISTINCT item_id FROM events WHERE batch_id = 0) p
    LEFT JOIN item_category_history h
      ON h.item_id = p.item_id
     AND h.valid_from = (SELECT MAX(h2.valid_from)
                           FROM item_category_history h2
                          WHERE h2.item_id = p.item_id AND h2.valid_from <= :cutoff)
""", params={"cutoff": cutoff.to_pydatetime()})
prods["category_id"] = prods["category_id"].astype("Int64")
print("Baseline products:", len(prods), "| with a category:", prods["category_id"].notna().sum())

run_batches("""
    UNWIND $rows AS r
    MERGE (p:Product {item_id: r.item_id})
""", to_rows(prods[["item_id"]]), label="Product nodes")

run_batches("""
    UNWIND $rows AS r
    MATCH (p:Product {item_id: r.item_id})
    MATCH (c:Category {category_id: r.category_id})
    MERGE (p)-[:BELONGS_TO]->(c)
""", to_rows(prods[prods["category_id"].notna()]), label="BELONGS_TO links")

Baseline cutoff time: 2015-07-21 20:32:23.468000
Baseline products: 188915 | with a category: 151393
Product nodes: 50,000 / 188,915
Product nodes: 100,000 / 188,915
Product nodes: 150,000 / 188,915
Product nodes: 188,915 / 188,915
Product nodes: finished

BELONGS_TO links: 50,000 / 151,393
BELONGS_TO links: 100,000 / 151,393
BELONGS_TO links: 150,000 / 151,393
BELONGS_TO links: 151,393 / 151,393
BELONGS_TO links: finished

*check the graph agains musql*

In [12]:
expected = {
    "Category nodes": len(cats),
    "CHILD_OF links": len(with_parent),
    "Product nodes": len(prods),
    "BELONGS_TO links": int(prods["category_id"].notna().sum()),
}

with driver.session(database="neo4j") as session:
    actual = {
        "Category nodes": session.run("MATCH (c:Category) RETURN count(c) AS n").single()["n"],
        "CHILD_OF links": session.run("MATCH ()-[r:CHILD_OF]->() RETURN count(r) AS n").single()["n"],
        "Product nodes": session.run("MATCH (p:Product) RETURN count(p) AS n").single()["n"],
        "BELONGS_TO links": session.run("MATCH ()-[r:BELONGS_TO]->() RETURN count(r) AS n").single()["n"],
    }

result = pd.DataFrame({"expected (MySQL)": expected, "in graph": actual})
result["match"] = result["expected (MySQL)"] == result["in graph"]
result

                  expected (MySQL)  in graph  match
Category nodes                1699      1699   True
CHILD_OF links                1644      1644   True
Product nodes               188915    188915   True
BELONGS_TO links            151393    151393   True

**visitors and what they did with products**

*a helper that sends a table to Neo4j in slices*

In [13]:
def run_df_batches(cypher, df, batch_size=5000, label="", every=20):
    total = len(df)
    with driver.session(database="neo4j") as session:
        for n, i in enumerate(range(0, total, batch_size), start=1):
            session.run(cypher, rows=to_rows(df.iloc[i:i + batch_size])).consume()
            if n % every == 0 or i + batch_size >= total:
                print(f"{label}: {min(i + batch_size, total):,} / {total:,}")
    print(f"{label}: finished\n")

expected_links = {}   # we fill this in as we load, for the final check

In [14]:
visitors = q("SELECT DISTINCT visitor_id FROM events WHERE batch_id = 0")
print("Visitors in baseline:", len(visitors))

run_df_batches("""
    UNWIND $rows AS r
    MERGE (:Visitor {visitor_id: r.visitor_id})
""", visitors, batch_size=10000, label="Visitor nodes")

Visitors in baseline: 840006
Visitor nodes: 200,000 / 840,006
Visitor nodes: 400,000 / 840,006
Visitor nodes: 600,000 / 840,006
Visitor nodes: 800,000 / 840,006
Visitor nodes: 840,006 / 840,006
Visitor nodes: finished

In [15]:
views = q("""
    SELECT visitor_id, item_id, COUNT(*) AS cnt, MIN(event_ts) AS first_ts, MAX(event_ts) AS last_ts
    FROM events
    WHERE batch_id = 0 AND event_type = 'view'
    GROUP BY visitor_id, item_id
""")
print("VIEWED links to create:", len(views), "| view events they cover:", int(views["cnt"].sum()))
expected_links["VIEWED"] = (len(views), int(views["cnt"].sum()))

run_df_batches("""
    UNWIND $rows AS r
    MATCH (v:Visitor {visitor_id: r.visitor_id})
    MATCH (p:Product {item_id: r.item_id})
    MERGE (v)-[x:VIEWED]->(p)
    SET x.count = r.cnt, x.first_ts = r.first_ts, x.last_ts = r.last_ts
""", views, label="VIEWED links")
del views

VIEWED links to create: 1273334 | view events they cover: 1599672
VIEWED links: 100,000 / 1,273,334
VIEWED links: 200,000 / 1,273,334
VIEWED links: 300,000 / 1,273,334
VIEWED links: 400,000 / 1,273,334
VIEWED links: 500,000 / 1,273,334
VIEWED links: 600,000 / 1,273,334
VIEWED links: 700,000 / 1,273,334
VIEWED links: 800,000 / 1,273,334
VIEWED links: 900,000 / 1,273,334
VIEWED links: 1,000,000 / 1,273,334
VIEWED links: 1,100,000 / 1,273,334
VIEWED links: 1,200,000 / 1,273,334
VIEWED links: 1,273,334 / 1,273,334
VIEWED links: finished

In [16]:
for event_type, rel in [("addtocart", "ADDED_TO_CART"), ("transaction", "PURCHASED")]:
    df = q(f"""
        SELECT visitor_id, item_id, COUNT(*) AS cnt, MIN(event_ts) AS first_ts, MAX(event_ts) AS last_ts
        FROM events
        WHERE batch_id = 0 AND event_type = '{event_type}'
        GROUP BY visitor_id, item_id
    """)
    print(rel, "links to create:", len(df), "| events they cover:", int(df["cnt"].sum()))
    expected_links[rel] = (len(df), int(df["cnt"].sum()))

    run_df_batches(f"""
        UNWIND $rows AS r
        MATCH (v:Visitor {{visitor_id: r.visitor_id}})
        MATCH (p:Product {{item_id: r.item_id}})
        MERGE (v)-[x:{rel}]->(p)
        SET x.count = r.cnt, x.first_ts = r.first_ts, x.last_ts = r.last_ts
    """, df, label=f"{rel} links")
    del df

ADDED_TO_CART links to create: 36506 | events they cover: 40649
ADDED_TO_CART links: 36,506 / 36,506
ADDED_TO_CART links: finished

PURCHASED links to create: 12642 | events they cover: 13339
PURCHASED links: 12,642 / 12,642
PURCHASED links: finished

In [17]:
rows = []
with driver.session(database="neo4j") as session:
    nv = session.run("MATCH (v:Visitor) RETURN count(v) AS n").single()["n"]
    rows.append(("Visitor nodes", len(visitors), nv))
    for rel, (exp_links, exp_events) in expected_links.items():
        rec = session.run(f"MATCH ()-[x:{rel}]->() RETURN count(x) AS links, sum(x.count) AS events").single()
        rows.append((f"{rel} links", exp_links, rec["links"]))
        rows.append((f"{rel} events (sum of counts)", exp_events, rec["events"]))

check = pd.DataFrame(rows, columns=["what", "expected (MySQL)", "in graph"]).set_index("what")
check["match"] = check["expected (MySQL)"] == check["in graph"]
check

                                      expected (MySQL)  in graph  match
what
Visitor nodes                                   840006    840006   True
VIEWED links                                   1273334   1273334   True
VIEWED events (sum of counts)                  1599672   1599672   True
ADDED_TO_CART links                              36506     36506   True
ADDED_TO_CART events (sum of counts)             40649     40649   True
PURCHASED links                                  12642     12642   True
PURCHASED events (sum of counts)                 13339     13339   True

*transaction nodes*

In [19]:
tx = q("""
    SELECT transaction_id, MIN(event_ts) AS first_ts, COUNT(*) AS line_count
    FROM events
    WHERE batch_id = 0 AND event_type = 'transaction' AND transaction_id IS NOT NULL
    GROUP BY transaction_id
""")
null_tx = q("SELECT COUNT(*) AS n FROM events WHERE batch_id = 0 AND event_type = 'transaction' AND transaction_id IS NULL")["n"][0]
print("Transactions:", len(tx), "| purchase events without a transaction ID:", null_tx)

run_df_batches("""
    UNWIND $rows AS r
    MERGE (t:Transaction {transaction_id: r.transaction_id})
    SET t.first_ts = r.first_ts
""", tx, batch_size=5000, label="Transaction nodes")

Transactions: 10563 | purchase events without a transaction ID: 0
Transaction nodes: 10,563 / 10,563
Transaction nodes: finished

*MADE links*

In [20]:
made = q("""
    SELECT DISTINCT transaction_id, visitor_id
    FROM events
    WHERE batch_id = 0 AND event_type = 'transaction' AND transaction_id IS NOT NULL
""")
print("MADE links to create:", len(made))

run_df_batches("""
    UNWIND $rows AS r
    MATCH (v:Visitor {visitor_id: r.visitor_id})
    MATCH (t:Transaction {transaction_id: r.transaction_id})
    MERGE (v)-[:MADE]->(t)
""", made, label="MADE links")

MADE links to create: 10563
MADE links: 10,563 / 10,563
MADE links: finished

*CONTAINS links transacton to product*

In [21]:
contains = q("""
    SELECT transaction_id, item_id, COUNT(*) AS quantity
    FROM events
    WHERE batch_id = 0 AND event_type = 'transaction' AND transaction_id IS NOT NULL
    GROUP BY transaction_id, item_id
""")
print("CONTAINS links to create:", len(contains), "| purchase events they cover:", int(contains["quantity"].sum()))

run_df_batches("""
    UNWIND $rows AS r
    MATCH (t:Transaction {transaction_id: r.transaction_id})
    MATCH (p:Product {item_id: r.item_id})
    MERGE (t)-[x:CONTAINS]->(p)
    SET x.quantity = r.quantity
""", contains, label="CONTAINS links")

CONTAINS links to create: 13253 | purchase events they cover: 13339
CONTAINS links: 13,253 / 13,253
CONTAINS links: finished

*check against MySQL, plus consistency checks across the graph*

In [23]:
with driver.session(database="neo4j") as session:
    g_tx   = session.run("MATCH (t:Transaction) RETURN count(t) AS n").single()["n"]
    g_made = session.run("MATCH ()-[r:MADE]->() RETURN count(r) AS n").single()["n"]
    rec    = session.run("MATCH ()-[x:CONTAINS]->() RETURN count(x) AS links, sum(x.quantity) AS qty").single()

check = pd.DataFrame(
    [("Transaction nodes", len(tx), g_tx),
     ("MADE links", len(made), g_made),
     ("CONTAINS links", len(contains), rec["links"]),
     ("CONTAINS quantity (sum)", int(contains["quantity"].sum()), rec["qty"])],
    columns=["what", "expected (MySQL)", "in graph"]).set_index("what")
check["match"] = check["expected (MySQL)"] == check["in graph"]
display(check)

with driver.session(database="neo4j") as session:
    # every PURCHASED link must be backed by a basket that contains that product
    unbacked = session.run("""
        MATCH (v:Visitor)-[:PURCHASED]->(p:Product)
        WHERE NOT EXISTS { (v)-[:MADE]->(:Transaction)-[:CONTAINS]->(p) }
        RETURN count(*) AS n
    """).single()["n"]
    print("PURCHASED links not backed by a basket (expected 0):", unbacked)

    print("\nWhole graph, nodes:")
    for r in session.run("MATCH (n) RETURN labels(n)[0] AS label, count(*) AS n ORDER BY n DESC"):
        print(f"  {r['label']:<12} {r['n']:>10,}")
    print("Whole graph, relationships:")
    for r in session.run("MATCH ()-[x]->() RETURN type(x) AS type, count(*) AS n ORDER BY n DESC"):
        print(f"  {r['type']:<14} {r['n']:>10,}")

                         expected (MySQL)  in graph  match
what
Transaction nodes                   10563     10563   True
MADE links                          10563     10563   True
CONTAINS links                      13253     13253   True
CONTAINS quantity (sum)             13339     13339   True

PURCHASED links not backed by a basket (expected 0): 0

Whole graph, nodes:
  Visitor         840,006
  Product         188,915
  Transaction      10,563
  Category          1,699
Whole graph, relationships:
  VIEWED          1,273,334
  BELONGS_TO        151,393
  ADDED_TO_CART      36,506
  CONTAINS           13,253
  PURCHASED          12,642
  MADE               10,563
  CHILD_OF            1,644

In [24]:
with driver.session(database="neo4j") as session:
    result = session.run("""
        MATCH (p1:Product)<-[:CONTAINS]-(t:Transaction)-[:CONTAINS]->(p2:Product)
        WHERE p1.item_id < p2.item_id
        RETURN p1.item_id AS product_1, p2.item_id AS product_2, count(t) AS bought_together
        ORDER BY bought_together DESC LIMIT 10
    """)
    display(pd.DataFrame(result.data()))

   product_1  product_2  bought_together
0     213834     445351               18
1     301721     369158                6
2      28789     132633                5
3     379520     432171                5
4     269773     379520                4
5     218794     461686                4
6     269773     432171                4
7      32581     461686                4
8     297145     307733                4
9     222604     312781                4

In [25]:
sub = pd.read_csv("tableau_exports/products_per_top_category_baseline.csv")
orphans = q("SELECT category_id FROM categories WHERE root_category_id IS NULL")["category_id"]

sub["kind"] = sub["top_level_category"].isin(orphans).map({True: "missing from tree", False: "true top-level"})
sub.groupby("kind").agg(categories=("top_level_category", "count"), products=("products", "sum"))

                categories  products
kind
true top-level          21    151393

In [2]:
import os
import pandas as pd

def cypher_table(query, **params):
    with driver.session(database="neo4j") as session:
        return pd.DataFrame(session.run(query, **params).data())

def export_graph_tables(snapshot):
    os.makedirs("tableau_exports", exist_ok=True)
    out = {}

    # 1) product pairs bought in the same basket (only pairs seen in at least 2 baskets)
    out["bought_together"] = cypher_table("""
        MATCH (p1:Product)<-[:CONTAINS]-(t:Transaction)-[:CONTAINS]->(p2:Product)
        WHERE p1.item_id < p2.item_id
        WITH p1, p2, count(t) AS bought_together
        WHERE bought_together >= 2
        RETURN p1.item_id AS product_1, p2.item_id AS product_2, bought_together
        ORDER BY bought_together DESC LIMIT 2000
    """)

    # 2) basket sizes (items per transaction; 6 or more are grouped)
    baskets = cypher_table("""
        MATCH (t:Transaction)-[c:CONTAINS]->(:Product)
        WITH t, sum(c.quantity) AS items
        RETURN items AS items_in_basket, count(*) AS baskets
        ORDER BY items_in_basket
    """)
    baskets["size_group"] = baskets["items_in_basket"].apply(lambda n: str(n) if n <= 5 else "6+")
    baskets = baskets.groupby("size_group", as_index=False)["baskets"].sum()
    baskets["sort_order"] = baskets["size_group"].apply(lambda s: 6 if s == "6+" else int(s))
    out["basket_sizes"] = baskets.sort_values("sort_order").reset_index(drop=True)

    # 3) products with the widest audience (most different visitors who viewed them)
    audience = cypher_table("""
        MATCH (v:Visitor)-[x:VIEWED]->(p:Product)
        WITH p, count(v) AS distinct_viewers, sum(x.count) AS total_views
        ORDER BY distinct_viewers DESC LIMIT 500
        RETURN p.item_id AS item_id, distinct_viewers, total_views
    """)
    audience["views_per_viewer"] = (audience["total_views"] / audience["distinct_viewers"]).round(2)
    out["product_audience"] = audience

    # 4) products per top-level category (each product counted under its latest known category)
    out["products_per_top_category"] = cypher_table("""
        MATCH (root:Category) WHERE NOT EXISTS { (root)-[:CHILD_OF]->() }
        MATCH (p:Product)-[:BELONGS_TO]->(:Category)-[:CHILD_OF*0..]->(root)
        RETURN root.category_id AS top_level_category, count(DISTINCT p) AS products
        ORDER BY products DESC
    """)

    for name, df in out.items():
        df.insert(0, "snapshot", snapshot)
        df.to_csv(f"tableau_exports/{name}_{snapshot}.csv", index=False)
        print(f"saved tableau_exports/{name}_{snapshot}.csv  ({len(df)} rows)")
    return out

In [3]:
tables = export_graph_tables("baseline")

b = tables["basket_sizes"]
print("\nBaskets in total (expect 10563):", int(b["baskets"].sum()))
print("Baskets with exactly 1 item (expect 8952):", int(b.loc[b["size_group"] == "1", "baskets"].iloc[0]))

a = tables["product_audience"]
print("\nProduct 5411 (expect 1669 distinct viewers, 1855 total views):")
display(a[a["item_id"] == 5411])

print("Top 5 pairs bought together (expect 213834 + 445351 first, with 18):")
display(tables["bought_together"].head(5))
print("Pairs saved (expect 656):", len(tables["bought_together"]))
print("Top-level categories saved (expect 21):", len(tables["products_per_top_category"]))

saved tableau_exports/bought_together_baseline.csv  (656 rows)
saved tableau_exports/basket_sizes_baseline.csv  (6 rows)
saved tableau_exports/product_audience_baseline.csv  (500 rows)
saved tableau_exports/products_per_top_category_baseline.csv  (21 rows)

Baskets in total (expect 10563): 10563
Baskets with exactly 1 item (expect 8952): 8952

Product 5411 (expect 1669 distinct viewers, 1855 total views):

   snapshot  item_id  distinct_viewers  total_views  views_per_viewer
0  baseline     5411              1669         1855              1.11

Top 5 pairs bought together (expect 213834 + 445351 first, with 18):

   snapshot  product_1  product_2  bought_together
0  baseline     213834     445351               18
1  baseline     301721     369158                6
2  baseline     379520     432171                5
3  baseline      28789     132633                5
4  baseline      32581     461686                4

Pairs saved (expect 656): 656
Top-level categories saved (expect 21): 21

In [4]:
from getpass import getpass
from neo4j import GraphDatabase
driver = GraphDatabase.driver("bolt://localhost:7688", auth=("neo4j", getpass("NEW Neo4j password: ")))
with driver.session(database="neo4j") as s:
    print("Nodes:", s.run("MATCH (n) RETURN count(n) AS n").single()["n"],
          "| Relationships:", s.run("MATCH ()-[r]->() RETURN count(r) AS n").single()["n"])

NEW Neo4j password:  ········

Nodes: 1041183 | Relationships: 1499335